bpweb/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'bpweb'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="bpweb/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    #url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

thesis_proj/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^bpweb/", include("bpweb.urls", namespace="bpweb")),
    url(r"^bpweb/", include("django.contrib.auth.urls")),
]

bpweb/models.py
from django.contrib import auth
from django.db import models
from django.utils import timezone

from django.contrib.auth.models import ( AbstractBaseUser, BaseUserManager )

class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),


        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active

bpweb/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


#class UserCreateForm(UserCreationForm):
#    class Meta:
#        fields = ("username", "email", "password1", "password2")
#        model = get_user_model()

#    def __init__(self, *args, **kwargs):
##        self.fields["username"].label = "Display name"
#        self.fields["email"].label = "Email address"

bpweb/views.py
from django.contrib.auth import login, logout
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView

from . import forms

#class SignUp(CreateView):
#    form_class = forms.UserCreateForm
#    success_url = reverse_lazy("login")
#    template_name = "bpweb/signup.html"

thesis_proj/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView


class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse("test"))
        return super().get(request, *args, **kwargs)

bpweb/templates/bpweb/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="row">
  <div class="col-md-8">
   <div class="jumbotron" style="background-color: #A9E2F3; margin-left: 45%; margin-top: 8%; margin-bottom: 30%;  width: 60%">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
</div>
{% endblock %}

bpweb/templates/bpweb/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="row">
  <div class="col-md-8">
   <div class="jumbotron" style="background-color: #A9E2F3; margin-left: 20%; margin-top: 8%; margin-bottom: 30%;  width: 100%">
    <h1>SignUp!</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

    <title>BP WEB!</title>
  </head>
  <body background="{% static '/images/landing/wallpaper-light.png'%}">
  <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand mynav" href="{% url 'home' %}">
      <img src="{% static '/images/landing/bp_logo.png'%}" alt="Ooops! No file found. " height="40" width="60">
      BPWEB
    </a>
    <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">

      {% if user.is_authenticated %}
            <li><a href="#">Post</a></li>
            <li><a href="#">Groups</a></li>
            <li><a href="#">Create Group</a></li>
            <li><a href="{% url 'bpweb:logout' %}" class="nav-link">Log out</a></li>
      {% else %}
            <li><a href="{% url 'bpweb:login' %}" class="nav-link">Log in</a></li>

      {% endif %}




      </ul>



  </div>
  </nav>
  <div class="container mycontent">
    {% block content %}

    {% endblock %}

  </div>

  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="row">

    <div class="col-md-4">
      <div class="card" style="width:75%; margin-left: 15%; margin-top: 11%">
        <img class="card-img-top" src="{% static 'images/landing/avatar-cat.png'%}" alt="Card image" style="width:100%">
        <div class="card-body">
          <h4 class="card-title"> Cat </h4>
          <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#firstModal"> Click Me </button>

          <!-- The Modal -->
          <div class="modal fade" id="firstModal">
            <div class="modal-dialog modal-lg" style="margin-top: 10%">
              <div class="modal-content">
              <!-- Modal Header -->
              <div class="modal-header">
                <h4 class="modal-title"> Cat </h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <!-- Modal body -->
              <div class="modal-body">
                I am a cat
              </div>
              <!-- Modal footer -->
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>

              </div> <!-- modal content -->
            </div> <!-- modal dialog -->
          </div> <!-- modal -->
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col-md-4 -->

    <div class="col-md-4">
      <div class="card" style="width:75%; margin-left: 11%; margin-top: 11%">
        <img class="card-img-top" src="{% static 'images/landing/avatar-dog.png'%}" alt="Card image" style="width:100%">
        <div class="card-body">
          <h4 class="card-title"> Dog </h4>
          <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#secondModal"> Click Me </button>

          <!-- The Modal -->
          <div class="modal fade" id="secondModal">
            <div class="modal-dialog modal-lg" style="margin-top: 10%">
              <div class="modal-content">
              <!-- Modal Header -->
              <div class="modal-header">
                <h4 class="modal-title"> Dog </h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <!-- Modal body -->
              <div class="modal-body">
                I am a dog
              </div>
              <!-- Modal footer -->
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>

              </div> <!-- modal content -->
            </div> <!-- modal dialog -->
          </div> <!-- modal -->
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col-md-4 -->

    <div class="col-md-4">
      <div class="card" style="width:75%; margin-left: 11%; margin-top: 11%">
        <img class="card-img-top" src="{% static 'images/landing/avatar-pig.png'%}" alt="Card image" style="width:100%">
        <div class="card-body">
          <h4 class="card-title"> Pig </h4>
          <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#thirdModal"> Click Me </button>

          <!-- The Modal -->
          <div class="modal fade" id="thirdModal">
            <div class="modal-dialog modal-lg" style="margin-top: 10%">
              <div class="modal-content">
              <!-- Modal Header -->
              <div class="modal-header">
                <h4 class="modal-title"> Pig </h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <!-- Modal body -->
              <div class="modal-body">
                I am a pig
              </div>
              <!-- Modal footer -->
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>

              </div> <!-- modal content -->
            </div> <!-- modal dialog -->
          </div> <!-- modal -->
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col-md-4 -->

  </div> <!-- row -->


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
{% endblock %}

templates/registration.html
{% extends "base.html" %}
{% load staticfiles  %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1> Thank you for registering </h1>
  {% else %}
    <h1> Register here! </h1>
    <h3> Fill out the form: </h3>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{% user_form.as_p %}}
        {{% profile_form.as_p %}}
        <input type="submit" name="" value="Register">
    </form>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>



</div>




{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>Thank you!</h1>



</div>




{% endblock %}